### ISSUE TITLE
Roadmap / Todos

### ISSUE THREAD

**Issue by luthfianto** [rilut/rust-numeral#1]
This is a continuously updated list of Todos. If you have a suggestion, comment to the issue. I will update the list if the suggestion fits in.
Please note that none of the items will be guaranteed to be implemented. If you want to make sure something is done, consider to contribute the code to rust-numeral, any help is welcome! 

**If you want to implement an item, please post it in this thread and I will mark it in the list so that we don't duplicate work.**
- [x] `format_time`
- [x] `unformat_time`. Thanks @bahrunnur!
- [ ] `format_number`
- [ ] `format_currency`
- [ ] `format_percentage`
- [ ] `unformat_numeral`
- [ ] language/locale support
- [ ] proper use of `String`/`&str`
